## Cosine Similarity Calculations
Cosine similarity is a measure of similarity between two non-zero vectors of an inner product space that measures the cosine of the angle between them. Similarity measures have a multiude of uses in machine learning projects; they come in handy when matching strings, measuring distance, and extracting features. This similarity measurement is particularly concerned with orientation, rather than magnitude. 
In this case study, you'll use the cosine similarity to compare both a numeric data within a plane and a text dataset for string matching.

Load the Python modules, including cosine_similarity, from sklearn.metrics.pairwise

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.cm as cm
%matplotlib inline
plt.style.use('ggplot')
from scipy import spatial
from sklearn.metrics.pairwise import cosine_similarity

**<font color='teal'> Load the distance dataset into a dataframe. </font>**

In [7]:
df = pd.read_csv("/Users/sarahberkin/Downloads/CosineSimilarityCaseStudy 2/distance_dataset (1).csv")

In [51]:
df.head()

Unnamed: 0         X         Y         Z  ClusterID
0           0  5.135779  4.167542  5.787635          4
1           1  4.280721  5.770909  6.091044          4
2           2  8.329098  7.540436  3.247239          2
3           3  5.470224  5.069249  5.768313          4
4           4  2.381797  2.402374  3.879101          1

### Cosine Similarity with clusters and numeric matrices

All points in our dataset can be thought of as feature vectors. We illustrate it here as we display the __Cosine Similarity__ between each feature vector in the YZ plane and the [5, 5] vector we chose as reference. The sklearn.metrics.pairwise module provides an efficient way to compute the __cosine_similarity__ for large arrays from which we can compute the similarity.

 **<font color='teal'> First, create a 2D and a 3D matrix from the dataframe. The 2D matrix should contain the 'Y' and 'Z' columns and the 3D matrix should contain the 'X','Y', and 'Z' columns.</font>**

In [45]:
TwoD = df[['Y', 'Z']].to_numpy()
TwoD_reshape = TwoD.reshape(2000,2)
TwoD_reshape.shape

(2000, 2)

In [49]:
print(TwoD_reshape[:5])

[[4.16754224 5.7876354 ]
 [5.77090875 6.0910442 ]
 [7.54043595 3.2472394 ]
 [5.06924901 5.76831344]
 [2.40237389 3.87910086]]


In [43]:
ThreeD = df[['X', 'Y', 'Z']].to_numpy()
ThreeD_reshape = ThreeD.reshape(2000, 3, 1)
ThreeD_reshape.shape

(2000, 3, 1)

In [53]:
print(ThreeD_reshape[:5])

[[[5.13577939]
  [4.16754224]
  [5.7876354 ]]

 [[4.2807207 ]
  [5.77090875]
  [6.0910442 ]]

 [[8.3290979 ]
  [7.54043595]
  [3.2472394 ]]

 [[5.47022447]
  [5.06924901]
  [5.76831344]]

 [[2.38179703]
  [2.40237389]
  [3.87910086]]]


Calculate the cosine similarity for those matrices with reference planes of 5,5 and 5,5,5. Then subtract those measures from 1 in new features.

In [57]:
simCosine3D = 1. - cosine_similarity(ThreeD_reshape, [[5,5,5]])
simCosine = 1. - cosine_similarity(TwoD_reshape, [[5,5]])

ValueError: Found array with dim 3. check_pairwise_arrays expected <= 2.

Using the 2D matrix and the reference plane of (5,5) we can use a scatter plot to view the way the similarity is calculated using the Cosine angle.

In [ ]:
figCosine = plt.figure(figsize=[10,8])

plt.scatter(df.Y, df.Z, c=simCosine[:,0], s=20)
plt.plot([0,5],[0,5], '--', color='dimgray')
plt.plot([0,3],[0,7.2], '--', color='dimgray')
plt.text(0.7,2.6,r'$\theta$ = 22.4 deg.', rotation=47, size=14)
plt.ylim([0,10])
plt.xlim([0,10])
plt.xlabel('Y', size=14)
plt.ylabel('Z', size=14)
plt.title('Cosine Similarity')
cb = plt.colorbar()
cb.set_label('Similarity with (5,5)', size=14)

#figCosine.savefig('similarity-cosine.png')

Now, plot the 3D matrix with the similarity and the reference plane, (5,5,5).

In [ ]:
from mpl_toolkits.mplot3d import Axes3D
figCosine3D = plt.figure(figsize=(10, 8))
ax = figCosine3D.add_subplot(111, projection='3d')

p = ax.scatter(mat[:,0], mat[:,1], mat[:,2], c=simCosine3D[:,0])
ax.set_xlabel('X')
ax.set_ylabel('Y')
ax.set_zlabel('Z')
cb = figCosine3D.colorbar(p)
cb.set_label('Similarity with (5,5,5)', size=14)
                                   
figCosine3D.tight_layout()
#figCosine3D.savefig('cosine-3D.png', dpi=300, transparent=True)

----

### Cosine Similarity with text data
This is a quick example of how you can use Cosine Similarity to compare different text values or names for record matching or other natural language proecessing needs. 
First, we use count vectorizer to create a vector for each unique word in our Document 0 and Document 1. 

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
count_vect = CountVectorizer()
Document1 = "Starbucks Coffee"
Document2 = "Essence of Coffee"

corpus = [Document1,Document2]

X_train_counts = count_vect.fit_transform(corpus)

pd.DataFrame(X_train_counts.toarray(),columns=count_vect.get_feature_names(),index=['Document 0','Document 1'])

Now, we use a common frequency tool called TF-IDF to convert the vectors to unique measures.

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
trsfm=vectorizer.fit_transform(corpus)
pd.DataFrame(trsfm.toarray(),columns=vectorizer.get_feature_names(),index=['Document 0','Document 1'])

Here, we finally apply the __Cosine Similarity__ measure to calculate how similar Document 0 is compared to any other document in the corpus. Therefore, the first value of 1 is showing that the Document 0 is 100% similar to Document 0 and 0.26055576 is the similarity measure between Document 0 and Document 1.

In [ ]:
cosine_similarity(trsfm[0:1], trsfm)

Replace the current values for `Document 0` and `Document 1` with your own sentence or paragraph and apply the same steps as we did in the above example.

 **<font color='teal'> Combine the documents into a corpus.</font>**

 **<font color='teal'> Apply the count vectorizer to the corpus to transform it into vectors.</font>**

 **<font color='teal'> Convert the vector counts to a dataframe with Pandas.</font>**

 **<font color='teal'> Apply TF-IDF to convert the vectors to unique frequency measures.</font>**

 **<font color='teal'> Use the cosine similarity function to get measures of similarity for the sentences or paragraphs in your original document.</font>**